### ISSUE TITLE
Add CODE_OF_CONDUCT file to repo

### ISSUE THREAD

**Issue by gregogun** [gregogun/portfolio-v2#1]
* Add 'CODE_OF_CONDUCT' markdown file in the root of the directory, taken from contributor covenant: https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

**Comment by kopalhedau** [comment]
hey can I work on this issue

**Comment by priyalHedau15** [comment]
Hey can I work on this issue

**Comment by gregogun** [comment]
> Hey can I work on this issue

Hey! sure, I'll assign you now :)
